import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Canvas, useFrame } from "@react-three/fiber";
import { Suspense } from 'react'
import { Sky } from '@react-three/drei'

// Import components
import PlayButton from '../components/PlayButton'
import CupModels from '../components/CupModel'
import Text from '../components/Text'
import AnimatedText from '../components/AnimatedText'

// Camera effects
function Dolly() {
  useFrame((state) => {
    state.camera.position.z = 7 + Math.sin(state.clock.getElapsedTime())
    state.camera.updateProjectionMatrix()
  })
  return null
}

const Home: NextPage = () => {

  const textOptions = {
    size: 1,
    height: 1,
    bevelEnabled: true,
    bevelSize: 0.05,
    bevelThickness: 0.05
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlayButton />
      <Canvas 
        id="teacup-field" 
        style={{height: '50vh'}}
        camera={{ near: 0.5, far: 15 }}
        >
        <Suspense fallback={
                <mesh>
                  <boxBufferGeometry args={[1, 1, 1]} />
                  <meshNormalMaterial />
               </mesh>
        }>
          <spotLight color="#61dafb" position={[-10, -10, -10]} intensity={0.2} />
          <spotLight color="#61dafb" position={[-10, 0, 15]} intensity={0.8} />
          <spotLight color="#61dafb" position={[-5, 20, 2]} intensity={0.5} />
          <spotLight color="#f2056f" position={[15, 10, -2]} intensity={2} />
          <spotLight color="#f2056f" position={[15, 10, 5]} intensity={1} />
          <spotLight color="#b107db" position={[5, -10, 5]} intensity={0.8} />
          <CupModels count={500} fieldScale={10} closeness={0} />
          <Text text="VANILLA" position={[0, 0, -1]} vAlign='center' hAlign='center' geomOptions={textOptions} />
          <Text text="TEA" position={[-1, -1, -1]} vAlign='center' hAlign='center' geomOptions={textOptions} />
          <Sky />
          <Dolly />
        </Suspense>
      </Canvas>
      <Canvas id="text-test" style={{height: '40vh'}}>
        <Suspense fallback={
                <mesh>
                  <boxBufferGeometry args={[1, 1, 1]} />
                  <meshNormalMaterial />
               </mesh>
        }>
          {/* <AnimatedText text="ANIMATED TEXT" geomOptions={textOptions} /> */}
        </Suspense>
      </Canvas>
    </div>
  )
}

export default Home
